### ISSUE TITLE
关于kaistVOC2yolo

### ISSUE THREAD

**Issue by engineerkobe** [Ye-zixiao/Double-YOLO-Kaist#12]
你好，我在转换格式的时候遇到了这个问题，不知道是否可以收获您的解答：
Traceback (most recent call last):
  File "trans_kaistvoc2yolo.py", line 167, in <module>
    main()
  File "trans_kaistvoc2yolo.py", line 155, in main
    for i, (tp, tn) in zip(txt_paths, voc_txt_names):
ValueError: too many values to unpack (expected 2)

**Comment by fairysli** [comment]
加enumerate
